# https://github.com/robvanderleek/create-issue-branch
mode: chatops
branchName: full
autoCloseIssue: true
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: issues/